id: I6F54ACD4
legacy_id: P006902
ocr_import_info:
  bdrc_scan_id: W1CZ1231
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T11:33:43'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T19:01:06.098363+00:00'
last_modified: 2022-08-31 03:01:21.263719
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ1231
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ1231
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྨན་པའི་ལག་ལེན་དོན་འདུས་སྙིང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.5137103863058257
  ocr_word_median_confidence_index: 0.4399999976158142
quality: null
bases:
  I1CZ1703:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ1703
      total_pages: 150
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ1703.txt
    statistics:
      ocr_word_median_confidence_index: 0.4399999976158142
      ocr_word_mean_confidence_index: 0.5137103863058257
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
